### ISSUE TITLE
Class Loader, Runtime Data Area, Execution Engine이란 무엇인가요?

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/backend-study#12]
### Class Loader, Runtime Data Area, Execution Engine이란 무엇인가요?

- [ ]  Class Loader, Runtime Data Area, Execution Engine 개념
- [ ] Class Loader, Runtime Data Area, Execution Engine의 특징

**Comment by ssibongee** [comment]
주제가 좀 큰 것 같은데 혹시 질문을 좀 더 세분화되어 구분해 주실 수 있으실까요? 
* Java 애플리케이션이 실행되는 과정
* JVM이 구동될 때 또는 종료될 때 어떠한 과정을 거치는지
* JVM 메모리구조와 클래스로더의 역할
위의 주제들이 혼재되어있는것 같습니다~ 하나의 질문에서 주제에 대한 내용을 모두 다루기에는 너무 큰 것 같은데 어떻게 생각하시나요??

**Comment by vincentj2** [comment]
네 그럼 클래스로더랑 메모리구조 관련해서 세분화 시킬게요~
