### ISSUE TITLE
JVM 이란 무엇인가요?

### ISSUE THREAD

**Issue by forest747** [Today-I-Learn/backend-study#3]
<h3>JVM 이란 무엇인가요? </h3>

- [x] JVM이란
- [x] JVM이 수행하는 일
- [x] JVM이 정의하는 것들
- [x] JVM의 장점과 단점
- [x] JVM은 단일 스레드로 동작하는지 멀티 스레드로 동작하는지
- [x] JVM, JRE, JDK의 개념과 차이점

**Comment by ssibongee** [comment]
* JVM은 단일 스레드로 동작하는지 멀티 스레드로 동작하는지
* JVM, JRE, JDK의 개념과 차이점

위의 내용에 대해서도 추가적으로 다루어 주셨으면 좋겠습니다~

**Comment by kcj3054** [comment]
1. 프로세스와 스레드의 차이점. 
2. 스레드와 멀티 스레드가 어떤 경우에 발생하는 경우
에 대해서도 공부하면 좋을거 같습니다.

**Comment by ssibongee** [comment]
> 1. 프로세스와 스레드의 차이점.
> 2. 스레드와 멀티 스레드가 어떤 경우에 발생하는 경우
>    에 대해서도 공부하면 좋을거 같습니다.

이 부분은 `JVM` 보다는 `OS` 의 프로세스와 스레드라는 주제와 더 어울리는것 같습니다~ 별도의 이슈로 분리해주셔도 좋을 것 같은데 어떻게 생각하시나요??
